services:
  db:
    image: postgres:13
    container_name: jungle-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jungle
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf  # Mount the custom configuration
    ports:
      - "5432:5432"
    networks:
      - jungle-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jungle-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/jungle?sslmode=disable
      DATA_LOADED: "true"
      CSV_FILE_PATH: /data/dataset.csv
    ports:
      - "8080:8080"
    volumes:
      - ./dataset.csv:/data/dataset.csv
    networks:
      - jungle-network

volumes:
  postgres-data:

networks:
  jungle-network:
    driver: bridge
